[package]
name = "nwidgets"
version = "0.1.0"
edition = "2021"
include = ["data/**/*", "src/**/*", "Cargo.toml", "assets/**/*"]

[dependencies]
gtk4 = "0.10.0"
gdk-pixbuf = "0.21.0"
webkit6 = "0.5.0"
webkit6-sys = "0.5.0"
gtk4-layer-shell = "0.6.3"
glib = "0.18.0"
gdk4 = "0.10.0"
freedesktop-desktop-entry = "0.5.0"
freedesktop-icons = "0.4.0"
walkdir = "2.5.0"
log = "0.4.22"
env_logger = "0.11.5"
dirs = "6.0.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
image = "0.25.1"
tokio = { version = "1", features = ["full", "macros", "rt-multi-thread"] }
anyhow = "1.0.86"
zbus = "4.1.1"
futures = "0.3.30"
libc = "0.2.153"
chrono = "0.4.38"
cpal = "0.15.3"
hound = "3.5.1"
base64 = "0.22.1"
parking_lot = "0.12.2"
once_cell = "1.19.0"
url = "2.5.2"
mime_guess = "2.0.5"
async-channel = "2.3.1"
resvg = "0.45.0"
usvg = "0.45.0"
uuid = { version = "1.18.1", features = ["v4"] }

[build-dependencies]
grass = "0.13"

[workspace]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = 3
