[package]
name = "nwidgets"
version = "0.1.0"
edition = "2021"
include = ["data/**/*", "src/**/*", "Cargo.toml", "assets/**/*"]

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed", tag = "v0.216.1", features = ["wayland"] }
gpui_tokio = { git = "https://github.com/zed-industries/zed", tag = "v0.216.1" }

anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
futures-util = "0.3"
parking_lot = "0.12"
chrono = "0.4"
zbus = "5.12.0"
once_cell = "1.19"
pipewire = "0.9.2"
image = "0.25"
smallvec = "1"
cef = { git = "https://github.com/tauri-apps/cef-rs", tag = "export-cef-dir-v143.7.0+143.0.14" }
cef-dll-sys = { git = "https://github.com/tauri-apps/cef-rs", tag = "export-cef-dir-v143.7.0+143.0.14" }
dirs = "6.0"

[dev-dependencies]
divan = "0.1"

[[bench]]
name = "benchmarks"
harness = false

[workspace]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
