[package]
name = "nwidgets"
version = "0.1.0"
edition = "2021"
include = ["data/**/*", "src/**/*", "Cargo.toml", "assets/**/*"]

[dependencies]
gpui = { git = "https://github.com/Niahex/zed", features = ["wayland"] }
gpui_tokio = { git = "https://github.com/Niahex/zed" }

anyhow = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "fs", "io-util", "process", "net"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
futures-util = "0.3"
parking_lot = "0.12"
chrono = "0.4"
zbus = "5.12.0"
once_cell = "1.19"
pipewire = "0.9.2"
image = "0.25"
smallvec = "1"
cef = { git = "https://github.com/tauri-apps/cef-rs", tag = "export-cef-dir-v143.7.0+143.0.14" }
cef-dll-sys = { git = "https://github.com/tauri-apps/cef-rs", tag = "export-cef-dir-v143.7.0+143.0.14" }
dirs = "6.0"

# Launcher dependencies
freedesktop-desktop-entry = "0.5.0"
freedesktop-icons = "0.4.0"
nucleo = "0.3.0"
numbat = "1.10.0"
libc = "0.2"
secret-service = { version = "5.1.0", features = ["rt-async-io-crypto-rust"] }
gio = "0.20"
lyon_tessellation = "1.0.16"

[dev-dependencies]
divan = "0.1"

[[bench]]
name = "benchmarks"
harness = false

[workspace]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
incremental = false

[profile.release.package."*"]
opt-level = 3
codegen-units = 16
